<?php
return array (
  'id' => 
  array (
    'field' => 'id',
    'sort' => true,
    'edit' => 'text',
    'title' => '文章id',
    'type' => 'text',
    'verify' => '',
    'maxlength' => '',
    'minlength' => '',
    'select' => '',
  ),
  'title' => 
  array (
    'field' => 'title',
    'sort' => true,
    'edit' => 'text',
    'title' => '标题',
    'type' => 'text',
    'verify' => '',
    'maxlength' => '',
    'minlength' => '',
    'select' => '',
  ),
  'images' => 
  array (
    'field' => 'images',
    'sort' => true,
    'edit' => 'text',
    'title' => '缩率图',
    'type' => 'text',
    'verify' => '',
    'maxlength' => '',
    'minlength' => '',
    'select' => '',
  ),
  'tags' => 
  array (
    'field' => 'tags',
    'sort' => true,
    'edit' => 'text',
    'title' => 'TAG标签',
    'type' => 'text',
    'verify' => '',
    'maxlength' => '',
    'minlength' => '',
    'select' => '',
  ),
  'channeltype_id' => 
  array (
    'field' => 'channeltype_id',
    'sort' => true,
    'edit' => 'text',
    'title' => '内容模型id',
    'type' => 'text',
    'verify' => '',
    'maxlength' => '',
    'minlength' => '',
    'select' => '',
  ),
  'templet' => 
  array (
    'field' => 'templet',
    'sort' => true,
    'edit' => 'text',
    'title' => '模版文件',
    'type' => 'text',
    'verify' => '',
    'maxlength' => '',
    'minlength' => '',
    'select' => '',
  ),
  'author' => 
  array (
    'field' => 'author',
    'sort' => true,
    'edit' => 'text',
    'title' => '作者',
    'type' => 'text',
    'verify' => '',
    'maxlength' => '',
    'minlength' => '',
    'select' => '',
  ),
  'source' => 
  array (
    'field' => 'source',
    'sort' => true,
    'edit' => 'text',
    'title' => '来源',
    'type' => 'text',
    'verify' => '',
    'maxlength' => '',
    'minlength' => '',
    'select' => '',
  ),
  'cat_id' => 
  array (
    'field' => 'cat_id',
    'sort' => true,
    'edit' => 'text',
    'title' => '文章栏目',
    'type' => 'text',
    'verify' => '',
    'maxlength' => '',
    'minlength' => '',
    'select' => '',
  ),
  'keywords' => 
  array (
    'field' => 'keywords',
    'sort' => true,
    'edit' => 'text',
    'title' => '关键词',
    'type' => 'text',
    'verify' => '',
    'maxlength' => '',
    'minlength' => '',
    'select' => '',
  ),
  'description' => 
  array (
    'field' => 'description',
    'sort' => true,
    'edit' => 'text',
    'title' => '描述',
    'type' => 'text',
    'verify' => '',
    'maxlength' => '',
    'minlength' => '',
    'select' => '',
  ),
  'permission' => 
  array (
    'field' => 'permission',
    'sort' => true,
    'edit' => 'text',
    'title' => '阅读权限',
    'type' => 'text',
    'verify' => '',
    'maxlength' => '',
    'minlength' => '',
    'select' => '',
  ),
  'allowreply' => 
  array (
    'field' => 'allowreply',
    'sort' => true,
    'edit' => 'text',
    'title' => '评论选项',
    'type' => 'text',
    'verify' => '',
    'maxlength' => '',
    'minlength' => '',
    'select' => '',
  ),
  'rank' => 
  array (
    'field' => 'rank',
    'sort' => true,
    'edit' => 'text',
    'title' => '排序值',
    'type' => 'text',
    'verify' => '',
    'maxlength' => '',
    'minlength' => '',
    'select' => '',
  ),
  'add_time' => 
  array (
    'field' => 'add_time',
    'sort' => true,
    'edit' => 'text',
    'title' => '发布时间',
    'type' => 'text',
    'verify' => '',
    'maxlength' => '',
    'minlength' => '',
    'select' => '',
  ),
  'user_id' => 
  array (
    'field' => 'user_id',
    'sort' => true,
    'edit' => 'text',
    'title' => '发布人id',
    'type' => 'text',
    'verify' => '',
    'maxlength' => '',
    'minlength' => '',
    'select' => '',
  ),
  'right' => 
  array (
    'fixed' => 'right',
    'title' => '操作',
    'width' => 125,
    'minWidth' => 125,
    'toolbar' => '#barDemo',
  ),
);